# 为因子相关性添加配置文件

# 回测开始日期
start_date : '20070131'
# 回测终止日期
end_date : '20170331'
# 股票池
universe : '全A'
# 频率
freq : '1m'

# 待测试因子列表文件
factor_list_file : 'D:/FactorLib/factor_corr/factor_list.py'

# 输出路径
output_dir : 'D:/FactorLib/factor_corr/output'